#!/usr/bin/env ruby

usage =<<EOF

      #{$0} sam anno
      ------------------------------------------------------
      * sam      :: sam_file
      * anno     :: annotation_file
      ------------------------------------------------------

      - VERSION 1 3/15/2013 --------------------------------

      ------------------------------------------------------
      Creates table with frequency for each gene
      GENE\tCHROMOSOME\tSTRAND\tSTART\tEND\t#_of_reads
      NM_001089558\tchr1\t+\t3799\t15140\t5342

                                                       by khayer

EOF

### Functions #######################################################
#####################################################################

def prepare_bed_file(bed_file)
  #[chr,low,high] => [Gene,strand,#of_reads]
  all_genes = Hash.new
  File.open(bed_file).each do |line|
    line.chomp!
    fields = line.split("\t")
    low = fields[4].to_i
    high = fields[5].to_i
    chr = fields[2]
    gene = fields[1]
    strand = fields[3]
    starts = fields[9]
    stops = fields[10]
    length = 0
    starts.each_with_index do |start,i|
      length += stops[i].to_i - start.to_i
    end
    all_genes[[chr,low,high]] = [gene,strand,length,0]
  end
  all_genes
end

### Main ############################################################
#####################################################################

if ARGV.length < 2
  puts usage
  exit
end

#{$0} vcf xls target control tlf wik phast homo

sam_file = ARGV[0]
annotation_file = ARGV[1]

all_genes = prepare_bed_file(annotation_file)
puts all_genes[[chr1,62325,66662]]