#!/usr/bin/env ruby
usage =<<EOF
      #{$0} annotated.vcf sorted_refGene.txt
EOF

if ARGV.length != 2
  puts usage
  exit
end

annotated_dir = ARGV[0]
ref_gene_dir = ARGV[1]
output_dir = File.new("china_200_promo",'w')

ref_gene_handle = File.open(ref_gene_dir,'r')
#`grep exon #{annotated_dir} > tmp`

while !ref_gene_handle.eof?
  k = 0
  #puts 'Hallo'
  gen_array = ref_gene_handle.readline().split(" ")
  #puts gen_array
  gen_name = gen_array[1]
  #k = gets `echo "hallo"`

  k = `grep -c -w #{gen_name} #{annotated_dir} `
  if k.to_i == 1
    output_dir.write(`grep exon #{annotated_dir} | grep  -w #{gen_name} #{annotated_dir} | awk '($6 >= 200)'`)
  end

end