#!/usr/bin/env ruby
usage =<<EOF
      #{$0} annotated.vcf sorted_refGene.txt
EOF

if ARGV.length != 2
  puts usage
  exit
end

annotated_dir = ARGV[0]
ref_gene_dir = ARGV[1]
output_dir = File.new("ens_150_promo",'w')
random = (rand*100).floor

ref_gene_handle = File.open(ref_gene_dir,'r')
`grep exon #{annotated_dir} | awk '($6 >= 150)' > tmp#{random}`
`awk '($6 >= 150) ' #{annotated_dir} > tmp2#{random}`
ref_gene_fraction = 100/ref_gene_handle.size

while !ref_gene_handle.eof?

  gen_array = ref_gene_handle.readline().split(" ")
  gen_name = gen_array[1]
  k = `grep -c -w #{gen_name} tmp2#{random} `
  if k.to_i == 1
    output_dir.write(` grep  -w #{gen_name} tmp#{random} `)
  end

end

File.delete("tmp"+ random.to_s, "tmp2"+ random.to_s)