#!/usr/bin/env ruby
usage =<<EOF
      #{$0} rum.sam refGene.txt
EOF

if ARGV.length != 2
  puts usage
  exit
end

sam = ARGV[0]
refGene = ARGV[1]

random = (rand*10000).floor
tmp_file_header = "tmp#{random}_header"
`grep @ #{sam} > #{tmp_file_header}`
tmp_file_reads = "tmp#{random}_reads"
`grep -v @ #{sam} > #{tmp_file_reads}`

tmp_file_output = "tmp#{random}_output"
output_handler = File.new(tmp_file_output, 'w')

tmp_file_annotations = "tmp#{random}_annotations"
annotations_handler = File.new(tmp_file_annotations, 'w')

# Finding Poly-A tails
reads_handler = File.open(tmp_file_reads,'r')
reads_handler.each do |line_fwd|
  line_rev = reads_handler.readline()
  case
  when line_fwd =~ /AATAAA|TTATTT/
    output_handler.write(line_fwd, line_rev)
    line_fwd = line_fwd.split(" ")
    location = line_fwd[2]
    position = line_fwd[3]

  when line_rev =~ /AATAAA|TTATTT/
    output_handler.write(line_fwd, line_rev)
    line_rev = line_rev.split(" ")

  end

end


# Read file
handler = File.open("~/Desktop/Poly-A/rum/RUM.sam")

while !handler.eof()
  puts handler.readline()
end

puts "HAHA"