#!/usr/bin/env ruby
usage =<<EOF
  #{$0} unsorted.vcf sorted.vcf locations
EOF

if ARGV.length != 3
  puts usage
  exit
end


#file = File.open(ARGV[0],'r')
locations = File.open(ARGV[2],'r')
sorted = File.open(ARGV[1], 'w')

`grep -v -e "\#" #{ARGV[0]} > tmp`
`grep -e "\#" #{ARGV[0]} > tmp2`
tmp2 = File.open('tmp2', 'r')
while !tmp2.eof?
  sorted.write(tmp2.readline())
end


while !locations.eof?
  position = locations.readline().chomp()
  `grep -w #{position} tmp | sort -k 2,2 -n > tmp2`
  #`grep -v -e "\#" " #{ARGV[0]} | grep -w #{position} | sort -k 2,2 -n > tmp`

  tmp2 = File.open('tmp2', 'r')
  while !tmp2.eof?
    sorted.write(tmp2.readline())
  end
end
