#!/usr/bin/env ruby
usage =<<EOF
      #{$0} ref_Gene.txt sorted_refGene.txt locations
EOF

if ARGV.length != 3
  puts usage
  exit
end


#file = File.open(ARGV[0],'r')
locations = File.open(ARGV[2],'r')
sorted = File.open(ARGV[1], 'w')

while !locations.eof?
  position = locations.readline().chomp()
  `grep -w #{position} #{ARGV[0]} | sort -k 5,5 -n > #{ARGV[0]}tmp`
  tmp = File.open(ARGV[0]+'tmp', 'r')
  while !tmp.eof?
    sorted.write(tmp.readline())
  end
  File.delete(ARGV[0]+'tmp')
end

